// packages/svelte/ds-global/src/lib/_work_in_progress/Modal/common/Header/Header.svelte
<script lang="ts">
  import { getModalContext } from "../../context.js";
  import { CloseButton } from "./common/index.js";
  import type { HeaderProps } from "./types.js";
  import "./styles.css";

  const componentCssClassName = "ds modal-header";

  let {
    class: className,
    children,
    closeButton = true,
    ...rest
  }: HeaderProps = $props();

  const modalContext = getModalContext();
</script>

<div class={[componentCssClassName, className]} {...rest}>
  <div class="title" id={modalContext.titleId}>
    {@render children?.()}
  </div>
  {#if closeButton === true}
    <CloseButton />
  {:else if closeButton}
    {@render closeButton()}
  {/if}
</div>

<!-- @component
`Modal.Header` carries the modal title and a close button. The title names the dialog through `aria-labelledby`.

Heading semantics are up to the caller — to add them, wrap the title in a heading of the right level.

By default the close button is a `Modal.Header.CloseButton`, already wired to close the Modal. Set `closeButton` to `false` to drop it, or to a snippet to render your own.

## Example Usage
```svelte
<Modal.Header>Discard pending review?</Modal.Header>

<Modal.Header>
  <h2>Discard pending review?</h2>
</Modal.Header>
```

@implements ds:global.subcomponent.modal-header
-->

// packages/react/ds-global/src/lib/pattern/Modal/common/Header/Header.tsx
import type React from "react";
import { Button } from "../../../../component/Button/index.js";
import { useModalContext } from "../../hooks/useModalContext.js";
import type { HeaderProps } from "./types.js";
import "./styles.css";

const componentCssClassName = "ds modal-header";

/**
 * Modal.Header subcomponent
 *
 * Carries the modal title and the optional dismiss control. The title describes
 * what the modal is for, giving the user context on what triggered it. Both the
 * title id (which names the dialog) and the dismiss wiring come from the Modal
 * context, so a composed header needs no props of its own.
 *
 * The title is not a heading element: headings structure the page's document
 * outline, and a modal opens from anywhere in it, so no heading level would be
 * right everywhere. The title names the dialog through `aria-labelledby`
 * instead, which is what a screen reader announces when the modal opens.
 *
 * @implements ds:global.subcomponent.modal-header
 */
const Header = ({
  children,
  titleId,
  undismissible = false,
  dismissLabel = "Close",
  onDismiss,
  className,
  ...props
}: HeaderProps): React.ReactElement => {
  const modal = useModalContext();

  return (
    <header
      className={[componentCssClassName, className].filter(Boolean).join(" ")}
      {...props}
    >
      <span className="title" id={titleId ?? modal.titleId}>
        {children}
      </span>
      {!undismissible && (
        <Button
          type="button"
          className="close"
          importance="tertiary"
          icon="close"
          aria-label={dismissLabel}
          onClick={onDismiss ?? modal.onDismiss}
        />
      )}
    </header>
  );
};

Header.displayName = "Modal.Header";

export default Header;
